name: Go

on:
  push:
    branches: [ "development", "master"]
  pull_request:
    branches: [ "development", "master"]

jobs:
  gobuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2

    - name: Linting
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53.3
        working-directory: ./backend
        args: --verbose

    - name: Build
      run: |
        cd backend/
        go build -v

    - name: Test
      run: |
        cd backend/
        go test -coverprofile=coverage.txt ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: /backend/coverage.txt
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
